# Generated by Django 4.1.4 on 2023-08-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['number'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
    ]
