# Generated by Django 4.1.4 on 2023-08-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_level_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название темы')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('quantity', models.IntegerField(verbose_name='Количество занятий')),
                ('text_1', models.TextField(verbose_name='Обратная связь 1')),
                ('text_2', models.TextField(verbose_name='Обратная связь 2')),
                ('text_3', models.TextField(verbose_name='Обратная связь 3')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.courses', verbose_name='Курс')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['number'],
            },
        ),
    ]
